#!/usr/bin/env bash
# Install nginx on web-01 server and configure

sudo apt-get -y udpate
sudo apt-get -y install nginx
sudo service start nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo rm /var/www/html/index.nginx-debian.html

sudo sed -i '/\[::\]:80 default_server/ a rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"' /etc/nginx/sites-available/default
