#!/usr/bin/env bash
# Install nginx on web-01 server and configure custom 404 page

# install and start nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

# configure custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i '/rewrite/ a \\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
