#!/usr/bin/env bash
# Install nginx and configure
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

# configure root query page
sudo echo "Hello World!" > /var/www/html/index.html
if [ -f /var/www/html/index.nginx-debian.html ]
then
    sudo rm /var/www/html/index.nginx-debian.html
fi

# configure custom header in http response
sudo sed -i "/\[::\]:80 default_server/ a \\n\tadd_header X-Served-By $hostname always;" /etc/nginx/sites-available/default

# restart server
sudo service nginx restart
