#!/usr/bin/env bash
# creates a file that contains it's PID
pidfile=/var/run/myscript.pid

echo $$ > $pidfile

_term() {
    echo "I hate the kill command"
    rm "$pidfile"
    exit
}

_quit() {
    rm "$pidfile"
    exit
}

_sigint() {
    echo "Y U no love me?!"
    exit
}

trap _term SIGTERM
trap _quit SIGQUIT
trap _sigint SIGINT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
