#!/usr/bin/env bash
# env command in the shebang is more portable than full path to the interpreter
x="0"
while [ $x -lt 10 ]
do
    if [ $x = 3 ]
    then echo "bad luck"
    elif [ $x = 7 ]
    then echo "good luck"
    else
	echo "Best School"
    fi
    x=$((x+1))
done
