#!/usr/bin/env bash
# env command in the shebang is more portable than full path to the interpreter
x="0"
y="1"
while [ $x -lt 13 ]
do
    echo "Hour: $x"
    y="1"
    while [ $y -lt 60 ]
    do
	echo $y
	y=$((y+1))
    done
    x=$((x+1))
done
